# .travis.yml
language: node_js
node_js:
- "10"

branches:
  only:
  - master
before_install:
  - npm install -g firebase-tools
install:
- npm install

before_script:
- git config --global user.name 'monthly-act'
- git config --global user.email 'monthly.with.act@gmail.com'

script:
- npm run test:unit
- npm run build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
