# .travis.yml
language: node_js
node_js:
- "10"

branches:
  only:
  - master

install:
- npm install

before_script:
- git config --global user.name 'monthly-act'
- git config --global user.email 'monthly.with.act@gmail.com'

script:
- npm run build

deploy:
  provider: s3
  access_key_id: $AWS_S3_ACCESS_KEY
  secret_access_key: $AWS_S3_SECRET_KEY
  bucket: "june-poll-web"
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  region: ap-northeast-2
